version: '3.7'
services:
  api:
    container_name: 'api'
    build: '.'
    env_file:
      - ./.env.production
    environment:
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - '80:8080'
    volumes:
      - '.:/go/src/app'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    volumes:
      - /$HOME/data:/var/db/data
